version: '3.8'

services:
  alur:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alur-app
    restart: always
    environment:
      - POLL_INTERVAL=1800
      - PYTHONUNBUFFERED=1
    volumes:
      - /opt/alur/data:/app/data
      - /opt/alur/logs:/app/logs
      - /opt/alur/conf:/app/application/conf:ro
      - /opt/alur/resources:/app/application/resources:ro
    depends_on:
      - db
    command: python application/main.py

  db:
    image: postgres:14
    container_name: alur-db
    restart: always
    environment:
      POSTGRES_DB: alur
      POSTGRES_USER: aluruser
      POSTGRES_PASSWORD: alurpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
