# Configuration file to manage resources, file paths, authentication, and pseudonymization settings

resources:
  - name: Condition
    priority: 1  # Priority 1: Fetch every 30 minutes, P2: 2 hours, P3: 12 hours, P4: 24 hours.
    aql_file: condition.yml
    mapping_file: condition.yml
    required_fields:
      - subject_id
    mapper_module: fhir_mapping.condition_mapper
    mapper_function: map_condition

fetch_by_date:
  enabled: true  # Enable or disable fetching by date
  start_date: "2024-05-29T00:00:00"
  end_date: "2024-08-02T00:00:00"  # Leave empty for open-ended fetch
  fetch_interval_hours: 1  # ✅ Set fetch frequency in hours (e.g., 6 hours)

polling:
  enabled: true  # ✅ Enable global polling
  interval_seconds: 1800  # ✅ Global polling every 30 minutes (1800 seconds)
  max_parallel_fetches: 3  # ✅ Limit concurrent fetches

priority_fetching:
  enabled: false  # ✅ Enable or disable priority-based fetching
  priority_levels:
    1: 30   # Fetch Priority 1 every 30 minutes
    2: 120  # Fetch Priority 2 every 2 hours
    3: 720  # Fetch Priority 3 every 12 hours
    4: 1440 # Fetch Priority 4 every 24 hours

paths:
  env_file: .env
  state_file: data/state.json
  temp_folder: data/temp
  db_file: data/aql2fhir.db
  log_folder: logs/logs

authentication:
  method: basic  # ✅ Supported options: basic, bearer, api_key

pseudonymization:
  GPAS: false  # Enable GPAS pseudonymization
  enabled: true  # Global switch to enable or disable pseudonymization
  use_deterministic_aes: true  # ✅ NEW: Use deterministic encryption if True
  elements_to_pseudonymize:
    composition_id: 
      enabled: true
      prefix: "COMPID-"
    subject_id: 
      enabled: true
      prefix: "PID_"
    encounter_id:
      enabled: true
      prefix: "FALLID_"
    Patient_DOB:
      enabled: false
    LaboranfoderungID:
      enabled: true
      prefix: "LAB_"
    CompositionID:
      enabled: true
      prefix: "COMPID_"
    bericht_id:
      enabled: true
      prefix: "BERID_"

database:
  name: sqlite  # Change to `postgres` for PostgreSQL
  host: localhost
  port: 5432
  user: postgres
  password: password
  database: aql2fhir

sanitize:
  enabled: true
  elements_to_sanitize:
    - Composition_ID
    - subjectID
    - encounter_id
    - Patient_DOB
    - LaboranfoderungID
    - CompositionID
    - BerichtID

processing:
  use_batch: false
  batch_size: 100  # ✅ Set batch size for processing

server_health_check:
  enabled: true
  retry_interval_seconds: 20  # ✅ Retry every 20 seconds
  max_retries: null  # ✅ Unlimited retries (use `null` instead of "unlimited")

query_retries:
  enabled: true
  retry_count: 3  # ✅ Maximum retries for failed queries
  retry_interval_seconds: 10  # ✅ Wait 10 seconds before retrying

logging:
  level: INFO  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  enable_console: true  # Enable console logging
  enable_file: true  # Enable file logging
  log_file: logs/application.log  # Path to the log file

processing:
  max_fhir_workers: 5  # ✅ Maximum concurrent FHIR requests (dynamically loaded)


# Example override paths for using absolute paths
# resources:
# paths:
#   state_file: /opt/AQL2FHIR/state/state.json
#   temp_folder: /opt/application/temp
#   db_file: /opt/AQL2FHIR/application/temp/db/Aql2FHIR.db
#   aql_folder: /opt/AQL2FHIR/application/openehr_aql
#   mapping_folder: /opt/AQL2FHIR/application/mappings
#   log_folder: /opt/AQL2FHIR/application/logs
